### ISSUE TITLE
Fail to load ComfyUI when launching stable diffusion webui

### ISSUE THREAD

**Issue by jasper2326** [ModelSurge/sd-webui-comfyui#110] opened 2023-08-10 01:00 UTC
*** Error loading script: comfyui.py
    Traceback (most recent call last):
      File "/root/ssd1/jhz/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/root/ssd1/jhz/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/root/ssd1/jhz/stable-diffusion-webui/extensions/sd-webui-comfyui/scripts/comfyui.py", line 3, in <module>
        from lib_comfyui import comfyui_context, global_state, platform_utils, external_code, default_workflow_types, comfyui_process
      File "/root/ssd1/jhz/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/global_state.py", line 53, in <module>
        sys.modules[__name__] = GlobalState(globals())
      File "/root/ssd1/jhz/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/global_state.py", line 12, in __init__
        setattr(self, k, v)
      File "/root/ssd1/jhz/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/global_state.py", line 29, in __setattr__
        GlobalState.setattr(item, value)
      File "/root/ssd1/jhz/stable-diffusion-webui/extensions/sd-webui-comfyui/lib_comfyui/ipc.py", line 12, in wrapper
        return function(*args, **kwargs)
    TypeError: 'staticmethod' object is not callable

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/24251084/483a1da0-b4da-443e-84ef-5a1c8c0a6240)

My head is AT 0faa28ee68f7396a96ce56ccc68713fdb5e9f765
Thanks for your help.

**Comment by ljleb** [comment] 2023-08-10 01:08
What did you do to get this error? I am unable to reproduce the the given information.

**Comment by ljleb** [comment] 2023-08-10 01:12
My bad, what I actually want to know is which environment are you running on? It seems to be unix/linux based.

**Comment by jasper2326** [comment] 2023-08-10 01:16
I am running on a Linux system

**Comment by ljleb** [comment] 2023-08-10 01:18
I was curious about which distribution, because this does not happen in every linux environment it seems.

In any case, I will push a fix in a couple of minutes, I think I know why the issue arises.

**Comment by jasper2326** [comment] 2023-08-10 01:20
FYI
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

**Comment by ljleb** [comment] 2023-08-10 01:36
@jasper2326 just merged #111, let us know if the problem is resolved.

**Comment by ljleb** [comment] 2023-08-10 23:58
Closing as no response from OP. I believe this should be fixed, but please do let us know if it isn't.

**Closed by ljleb** 2023-08-10 23:58 UTC
Labels: bug
