### ISSUE TITLE
ComfyUI process is unexpectedly invoking launch_util

### ISSUE THREAD

**Issue by wfjsw** [ModelSurge/sd-webui-comfyui#74] opened 2023-07-21 12:49 UTC
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11856

It appears to me that the subprocess the extension launched has invoked `modules/launch_util.py` and in turn activated a `start` timer. This looks unexpected. Is there any way to mitigate this?

**Comment by ljleb** [comment] 2023-07-21 13:27
This is caused by the new process importing webui modules to reuse code. As webui modules are imported in a new subprocess, modules that are already imported have to be redefined, since processes do not share memory contrary to threads.

We will fix it on our side, you can close the issue in auto's repo.

**Comment by wfjsw** [comment] 2023-07-21 13:27
Thank you!

**Closed** 2023-07-23 15:19 UTC
Labels: bug
