### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NewmanMaxx** [ModelSurge/sd-webui-comfyui#170] opened 2023-11-01 02:56 UTC
Not working =)
I have ComfyUI installed as extension in Auto1111(portable) and its not working for me, also i have ComfyUiPortable on another folder and its work fine, but integrated as extention doesnt work.
![qweqweqwe](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/0e8bb954-b9ae-42b7-b42c-00f270fbbd52)
Path of SD(Portable) and extension ComfyUI is D:\stable-diffusion-portable-main\extensions\sd-webui-comfyui - its not working
Path of ComfyUI(standalone portable) D:\ComfyUI_windows_portable\ComfyUI - its working fine, but not extension
If i change standart "ComfyUI install location" to D:\ComfyUI_windows_portable\ or D:\ComfyUI_windows_portable\ComfyUI its still dont working with same issue.
![werwerwer](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/7a7949a6-5d65-4a40-b650-43e747e755f5)
Console writing
![ewqewqeqw](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/46b531a2-a6c0-4f52-a933-0b953bf10f89)
Versions
![ertertert](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/845c309d-6607-4757-bf8d-b1093d9a0059)

**Comment by ljleb** [comment] 2023-11-01 03:01
Change path to comfyui from `D:\stable-diffusion-portable-main\extensions\sd-webui-comfyui` to `D:\ComfyUI_windows_portable\ComfyUI`

**Comment by NewmanMaxx** [comment] 2023-11-01 03:23
First variant i tried already before and nothing changes.
With second variant ComfyUI tab proposed me to install ComfyUI 
![asdasdasd](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/6fb7c398-f998-4469-850d-fc6ff13e0266)
so its create new folder D:\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI and still doesnt work, no connection

**Comment by NewmanMaxx** [comment] 2023-11-01 03:28
btw if console wrote "ModuleNotFoundError: No module named 'Folder_paths'" now its write 
![sdfsdfsdf](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/b4dbbb3a-2a7b-4ed6-9c83-39caa45553c6)

**Comment by John-WL** [comment] 2023-11-01 04:02
I think this could be the same thing as #149

**Comment by NewmanMaxx** [comment] 2023-11-01 04:16
i think i solved it but dunno is in right way.
So i have SD(portable) --- D:\stable-diffusion-portable-main
ComfyUI(portable) --- D:\ComfyUI_windows_portable\ComfyUI (its work fine)
Installed ComfyUI extension in SD, indicate path in ComfyUI settings to portable version (D:\ComfyUI_windows_portable\ComfyUI).
Changed Address of the ComfyUI server on http://127.0.0.1:8188.
And its work fine in ComfyUI TAB in SD, but only when both launched (webui-user of SDPortable AND run_nvidia_gpu from ComfyUIPortable). Dunno should run_nvidia_gpu be running every time i want use ComfyUI as tab in SD

**Comment by ljleb** [comment] 2023-11-01 04:19
This won't work, the extension will not be able to communicate with comfyui like this. Can you try switching the IPC strategy in the settings for "File System"?

**Comment by ljleb** [comment] 2023-11-01 04:21
In the meantime I'll see if I can fix the code. I'm not sure why the shared memory is already created, probably an edge case.

**Comment by NewmanMaxx** [comment] 2023-11-01 04:25
with this settings still doesnt work when "webui-user.bat" of SDPortable only launched
![Uploading asdasd.png…]()

**Comment by ljleb** [comment] 2023-11-01 04:26
Are there any messages in the console?

**Comment by NewmanMaxx** [comment] 2023-11-01 04:28
when i removing ComfyUI server adress its never works, when i type http://127.0.0.1:8188/ its work, but only when "run_nvidia_gpu.bat" launched

**Comment by ljleb** [comment] 2023-11-01 04:29
Yes, try it again with the "file system" IPC strategy and please share what the console outputs.

**Comment by NewmanMaxx** [comment] 2023-11-01 04:36
with this settings 
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/0acb8850-195f-4c0c-af66-8fa52f484b9e)
ComfyUI tab doesnt work in any way until i add http://127.0.0.1:8188/ as server adress and doesnt matter which ICS (Deafault, Shared or File System)

**Comment by NewmanMaxx** [comment] 2023-11-01 04:40
with --port 8188 in Additional cli still wont work

**Comment by NewmanMaxx** [comment] 2023-11-01 04:40
with which settings you want to see console

**Comment by NewmanMaxx** [comment] 2023-11-01 04:42
if i launch with this 
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/c2d1c7aa-802b-4d38-a052-d1989e7c2d8b)
so 
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/9fd9f920-d8c3-4b4c-88c0-38dbc48bb85f)

**Comment by ljleb** [comment] 2023-11-01 05:05
I'm really puzzled here, unable to reproduce. I will try to install your portable versions to debug. Could you share the repos you are using?

**Comment by NewmanMaxx** [comment] 2023-11-01 05:06
what is repos ))) sry im not strong in all of it

**Comment by ljleb** [comment] 2023-11-01 05:08
Sorry, I meant to ask: how do I install the portable versions of the webui and comfyui you are using? are there github repositories somewhere that I can clone or download?

**Comment by NewmanMaxx** [comment] 2023-11-01 05:09
sec

**Comment by ljleb** [comment] 2023-11-02 19:16
So I tested a complete reinstall against stable-diffusion-portable and after a few hurdles, it is working. Somehow, this version of stable diffusion does not install extension dependencies. The error I got is different from what you ran into, so I'm not sure what's going on. I'll work on a fix with the shared memory by closing the shm if it exists.

**Comment by ljleb** [comment] 2023-11-02 21:13
Well I'm confused because the shm is already getting closed before trying to open it again. I don't know much about using shared memory and I ran into a core bug of the python library when trying to implement this the first time. If anyone knows how to fix this, I'd be glad to have a hand.

As a side note, something you could try @NewmanMaxx is to install the webui yourself using the official v1.0.0-pre zip:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre

If sd-webui-comfyui works through this other installation, then I assume the problem comes somewhere from the webui you are using. In this case, we may or may not intend to support it, depending on how much help this issue gets and where the issue comes from.

**Comment by alexbofa** [comment] 2023-11-03 07:58
In Stable Diffusion in `webui-user.bat` there is a line `set TEMP=`. In [Portable Stable Diffusion](https://github.com/serpotapov/stable-diffusion-portable#portable-stable-diffusion) there is `set TEMP=tmp`, but if you change `set TEMP=temp`, the extension will work.

**Comment by NewmanMaxx** [comment] 2023-11-03 08:17
it works
![qweqweqwe](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/a2bf6621-d335-419c-8514-61e8e4274cb0)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/58745c6f-1f6f-4883-8be5-a695b8f6cde5)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/149550916/14ba515f-d1bd-4655-809f-b595ed5882e4)

seems like solved atleast for me, would be nice to add that info in ComfyUI description maybe as interaction with SDPortable :3

**Comment by alexbofa** [comment] 2023-11-03 08:56
The main note. 
If we want to specify the already installed ComfyUI `Settings>ComfyUI>Computer install location` in the path as an example: `D:\Portable-ComfyUI\ComfyUI`, then `Load ComfyUI iframes through a reverse proxy (requires reload UI. Needs --api. Default is on if webui is remote): Always`. Don't forget to specify `set COMMANDLINE_ARGS=--api` in `webui-user.bat`

**Comment by ljleb** [comment] 2023-11-03 08:58
By the way @alexbofa do you understand what the problem was and why changing the `TMP` environment variable fixes it? I can't make much sense of it right now. I assume it is related to how shared memory is implemented with respect to the temporary folder?

**Closed** 2023-11-03 09:28 UTC
Labels: bug

**Comment by ljleb** [comment] 2023-11-03 14:33
With a fresh install, there should not be any "ComfyUI" directory anywhere in the repo. Where does it come from in the situation you are describing? We tested this quite a bit if I remember correctly, but let me try to do a fresh install to verify this again.
