### ISSUE TITLE
Could not find ComfyUI under Directory "<path to the extension>". The server will NOT be started

### ISSUE THREAD

**Issue by Hectorhammett** [ModelSurge/sd-webui-comfyui#163] opened 2023-09-25 00:12 UTC
Like the title says.

I installed it via the Automatic1111 extensions list and after giving me that error, I tried installing it from the github link, giving me the exact same error. I see the tab on Automatic1111 UI but nothing is in it. Not sure what's going on.

I am using:
Windows 11
Automatic version: 1.6.0
GPU: RTX 3090
CPU: Ryzen 7 5800X3D

**Comment by ljleb** [comment] 2023-10-16 03:13
Normally, right after installing the extension, you have to install comfyui. You can either do this manually or by following the instructions in the ComfyUI tab.

Here it seems that the tab does not load for some reason. Does it work if you git clone comfyui at `extensions/sd-webui-comfyui/ComfyUI`? To do this, you can either run the `install_comfyui.py` script manually from a command line interface or clone https://github.com/comfyanonymous/ComfyUI after changing directory to `extensions/sd-webui-comfyui`.

**Comment by John-WL** [comment] 2023-10-29 15:52
Closing this for now as there is no answer from op. Feel free to open it again if the issue is still there.

**Closed** 2023-10-29 15:53 UTC
Labels: bug
