### ISSUE TITLE
Image generation stuck at 95% when ComfyUI extension is enabled

### ISSUE THREAD

**Issue by lucadreamz** [ModelSurge/sd-webui-comfyui#194] opened 2023-12-21 06:30 UTC
Suddenly I'm having an issue where if I use a1111 with the ComfyUI extension where, when it's enabled, no images can be generated within a1111.  Even if I'm not using the extension.  It gets stuck at 95% and then doesn't proceed.  It works fine when the extension is disabled.

**Comment by ljleb** [comment] 2023-12-21 15:11
Thanks for letting us know. I am currently unable to reproduce the problem with the given information.

Here's a list of things to check:
- is the extension up to date?
- is ComfyUI up to date?
- is the webui up to date? (v1.7.0)

If the issue occurs on the latest versions:
- please share the full webui logs (from the start) in case it could contain useful information
- did anything change recently in your environment? it's fine if you don't know
- which extension are enabled when the issue occurs? does the error still occur if only the comfyui extension is enabled?

**Comment by lucadreamz** [comment] 2023-12-21 18:17
-     is the extension up to date?
-     is ComfyUI up to date?
-     is the webui up to date? (v1.7.0)

Yes to all three.  I just checked for updates again to ensure this and it's still stalling at the last part of the picture generation.

-     please share the full webui logs (from the start) in case it could contain useful information

Do you mean what's shown in the terminal?  Or is there a more detailed log you'd like me to pull?

-     did anything change recently in your environment? it's fine if you don't know

Not that I can think of.  It just starting doing this randomly and I had to disable the extension.  I tried uninstalling it by deleting the extension folder then reinstalling it but that didn't work.

-     which extension are enabled when the issue occurs? does the error still occur if only the comfyui extension is enabled?

Here is my list of extensions.  They are all enabled.


</body>
</html>--sd-webui-ar-plus 	https://github.com/LEv145/--sd-webui-ar-plus 	main 	[cbb397e7](https://github.com/LEv145/--sd-webui-ar-plus/commit/cbb397e70080fe677150e3c6dc81f3d73d4475f2) 	2023-11-28 10:30:35 	unknown
CFG_Rescale_webui 	https://github.com/Seshelle/CFG_Rescale_webui 	main 	[6accaf4e](https://github.com/Seshelle/CFG_Rescale_webui/commit/6accaf4e95bc8b329510871fffed06ae6b4e0cf0) 	2023-11-20 10:51:20 	unknown
adetailer 	https://github.com/Bing-su/adetailer 	main 	[261f9c1e](https://github.com/Bing-su/adetailer/commit/261f9c1edad38d7b61ede3550e29a7ffa54e58fb) 	2023-11-19 06:08:42 	unknown
canvas-zoom 	https://github.com/richrobber2/canvas-zoom.git 	main 	[26450143](https://github.com/richrobber2/canvas-zoom/commit/26450143c5115a587c022ddd88f7dc7dd9778611) 	2023-12-12 12:26:16 	unknown
clip-interrogator-ext 	https://github.com/pharmapsychotic/clip-interrogator-ext.git 	main 	[0f1a4591](https://github.com/pharmapsychotic/clip-interrogator-ext/commit/0f1a4591f82b93859a1b854afb79494f39384662) 	2023-09-09 18:35:46 	unknown
infinite-zoom-automatic1111-webui 	https://github.com/v8hid/infinite-zoom-automatic1111-webui.git 	main 	[d6461e7d](https://github.com/v8hid/infinite-zoom-automatic1111-webui/commit/d6461e7daad5f164f947d28e141fff5167537a67) 	2023-09-04 18:11:31 	unknown
openOutpaint-webUI-extension 	https://github.com/zero01101/openOutpaint-webUI-extension.git 	main 	[522c1878](https://github.com/zero01101/openOutpaint-webUI-extension/commit/522c1878fa71f27c6ac009aca925aeb4fc6dc32d) 	2023-12-16 04:36:06 	unknown
sd-dynamic-prompts 	https://github.com/adieyal/sd-dynamic-prompts.git 	main 	[2f36e0ff](https://github.com/adieyal/sd-dynamic-prompts/commit/2f36e0ff835ae0874faa3cfe90ed57eb76cef7ac) 	2023-12-11 08:58:02 	unknown
sd-webui-animatediff 	https://github.com/continue-revolution/sd-webui-animatediff.git 	master 	[55ecff36](https://github.com/continue-revolution/sd-webui-animatediff/commit/55ecff365615aee28292ccbcea4c1de65b224fe6) 	2023-12-19 19:31:21 	unknown
sd-webui-comfyui 	https://github.com/ModelSurge/sd-webui-comfyui.git 	main 	[8153a69a](https://github.com/ModelSurge/sd-webui-comfyui/commit/8153a69a4db0bb9027169a4462aa6c37d2e20cba) 	2023-12-19 19:28:19 	unknown
sd-webui-controlnet 	https://github.com/Mikubill/sd-webui-controlnet 	main 	[01e4574d](https://github.com/Mikubill/sd-webui-controlnet/commit/01e4574d8e01fa00628fdae0c8215283a1c36a8d) 	2023-12-17 23:19:59 	unknown
sd-webui-controlnet-fastload 	https://github.com/pk5ls20/sd-webui-controlnet-fastload.git 	main 	[bbdb929f](https://github.com/pk5ls20/sd-webui-controlnet-fastload/commit/bbdb929f4285ea69d5099268496e4322dc7203ab) 	2023-09-17 00:02:00 	unknown
sd-webui-mov2mov 	https://github.com/Scholar01/sd-webui-mov2mov.git 	master 	[e4e96e78](https://github.com/Scholar01/sd-webui-mov2mov/commit/e4e96e7836159b5a58794a1bdf0acce31b9b1271) 	2023-11-04 20:11:59 	unknown
sd-webui-reactor 	https://github.com/Gourieff/sd-webui-reactor 	main 	[805a0cae](https://github.com/Gourieff/sd-webui-reactor/commit/805a0cae176cf7fd14975bcf7bab8923eda08efe) 	2023-12-19 12:54:21 	unknown
sd-webui-regional-prompter 	https://github.com/hako-mikan/sd-webui-regional-prompter.git 	main 	[3a759b72](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/3a759b726a9e37d75bc0a5485c85084d14820cdc) 	2023-12-18 06:21:18 	unknown
sd_dreambooth_extension 	https://github.com/d8ahazard/sd_dreambooth_extension.git 	main 	[113708fd](https://github.com/d8ahazard/sd_dreambooth_extension/commit/113708fdaab97ff905c646b92c9a1bd17af8941f) 	2023-12-20 11:27:21 	unknown

**Comment by ljleb** [comment] 2023-12-22 04:54
> Do you mean what's shown in the terminal? Or is there a more detailed log you'd like me to pull?

Yes, please show the entire output of the webui console until it hangs after clicking on generate.

> Here is my list of extensions. They are all enabled.

That is a lot of extensions. I'm suspecting this is caused by an extension conflict. Does the problem still occur if you disable them all except sd-webui-comfyui? you should be able to save state and then restore after unchecking them all except this one.

**Comment by lucadreamz** [comment] 2024-01-03 03:44
Hi - this is confirmed it was caused by extension conflict.  I couldn't identify which one but just wanted to circle back.

**Comment by ljleb** [comment] 2024-01-05 17:24
Thanks. I'll close this since we don't know which extension it is. Feel free to open a new issue if you isolate it and want us to do something about it.

**Closed by ljleb** 2024-01-05 17:24 UTC
