### ISSUE TITLE
--listen will always load on the local machine the server is running, and will not listen to all no matter what

### ISSUE THREAD

**Issue by Charmandrigo** [ModelSurge/sd-webui-comfyui#161] opened 2023-09-16 22:11 UTC
as the name says I run this on a different machine and log in locally from my work PC, my webui always listens to 0.0.0.0 which makes it visible on the whole local network.
This addon will always listen to 127.0.0.1 (the local machine comfyui is running), it does not work on local network machines connected to webui.
I tried to add the cli argument "--listen 0.0.0.0" but did not worked and always publishes the URL on the local machine only. 
I _need_ it to listen 0.0.0.0:(default port) otherwise I can't see the page

**Comment by ljleb** [comment] 2023-09-19 06:15
Does this situation happen in newer versions of comfyui only? I suspect this is a bug caused by refactoring cli args code in recent commits in the comfyui repo: https://github.com/comfyanonymous/ComfyUI/commit/3039b08eb16777431946ed9ae4a63c5466336bff

**Comment by ljleb** [comment] 2023-09-19 06:18
Pushed a fix for #160, let me know if it fixes this as well.

**Comment by ljleb** [comment] 2023-09-20 17:56
Closing this for now, but will reopen if this is still a problem.

**Closed by ljleb** 2023-09-20 17:56 UTC

**Comment by Charmandrigo** [comment] 2023-09-27 22:02
> Pushed a fix #162 for #160, let me know if it fixes this as well.

Thanks! It worked "--listen 0.0.0.0" now makes it accessible on all local network
