### ISSUE TITLE
ComfyUI manager - Unsecure Feature is disabled

### ISSUE THREAD

**Issue by ericlinyi1** [ModelSurge/sd-webui-comfyui#218] opened 2024-05-12 16:18 UTC
Hi all,

I am facing the below error when try to down the missing nodes using the comfyui manager, please help to advise how to solve the issue.

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
**ERROR: The unsecure feature is disabled, restricting the installation of custom nodes. Please contact the administrator.**
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]

**Comment by PladsElsker** [comment] 2024-05-12 17:20
This is a problem related to the ComfyUI Manager repository, which is not handled by this extension. This extension is only an adapter for ComfyUI to work in the Webui. 

I believe you should open an issue in the manager repository instead:
https://github.com/ltdrdata/ComfyUI-Manager

**Comment by PladsElsker** [comment] 2024-05-12 17:22
Will close this for now, do open it back again if the issue is actually related to sd-webui-comfyui extension.

**Closed as not planned** 2024-05-12 17:22 UTC
