### ISSUE TITLE
No module named 'app.user_manager'

### ISSUE THREAD

**Issue by silveroxides** [ModelSurge/sd-webui-comfyui#206] opened 2024-01-16 10:47 UTC
Getting this error at every startup. Attempt at reinstalling failed. Seems it tries to use sd-webui environment path when loading modules. My sd-webui is the standalone portable version for windows. [sysinfo](https://pastebin.com/6FvzmwmT)

```
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
[sd-webui-comfyui] Created a reverse proxy route to ComfyUI: /sd-webui-comfyui/comfyui
Startup time: 64.5s (prepare environment: 20.2s, import torch: 7.1s, import gradio: 1.4s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.7s, opts onchange: 0.4s, setup codeformer: 0.3s, list SD models: 1.0s, load scripts: 12.7s, scripts before_ui_callback: 7.4s, create ui: 6.8s, gradio launch: 4.4s, app_started_callback: 0.8s).
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: Shared memory
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
[ComfyUI] Total VRAM 16380 MB, total RAM 32716 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[ComfyUI] xformers version: 0.0.20
[ComfyUI] Set vram state to: NORMAL_VRAM
[ComfyUI] Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
[ComfyUI] VAE dtype: torch.bfloat16
[ComfyUI] Using xformers cross attention
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 98, in <module>
    main()
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 43, in main
    patch_comfyui()
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 86, in patch_comfyui
    routes_extension.patch_server_routes()
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\routes_extension.py", line 8, in patch_server_routes
    add_server__init__patch(websocket_handler_patch)
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\lib_comfyui\comfyui\routes_extension.py", line 13, in add_server__init__patch
    import server
  File "D:\stable-diffusion-webui\webui\extensions\sd-webui-comfyui\ComfyUI\server.py", line 33, in <module>
    from app.user_manager import UserManager
ModuleNotFoundError: No module named 'app.user_manager'
```

**Comment by ljleb** [comment] 2024-01-20 10:36
It looks like comfyui isn't able to see its own python modules. I suspect this is a pythonpath bug again, though I'm not sure how it wouldn't be set up properly. It should point to the comfyui dir after the comfyui subprocess is started, so this is weird.

Can you try installing comfyui manually in a different dirrectory maybe, and then point the comfyui dir to it in the settings? Make sure to restart the webui after. I'm not certain this fixes the problem, I'm just blind guessing.

**Comment by PladsElsker** [comment] 2024-02-26 17:20
Closing this for now because no answer from op.

**Closed** 2024-02-26 17:20 UTC

**Comment by silveroxides** [comment] 2024-03-10 10:04
> Closing this for now because no answer from op.

Sorry about that. I decided to not bother with it and set up comfyUI manually as an independent repo. So this extension per se is not what I am looking for anymore since I would rather handle stuff entirely over fastapi from the comfyUI side if I need to use anything in sd-webui

**Comment by YacratesWyh** [comment] 2024-06-18 02:40
It seems caused by some pypi pack, as I got the same problem in comfy when I tryied to install panfusion, and no idea what caused it.
